[package]
name = "ns73m"
version = "0.1.0"
authors = ["Jesse Braham <jesse@beta7.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.2.1"
embedded-hal = "1.0.0-alpha.4"
